export type BlogCardType = {
  id: number;
  img: string;
  createdAt: string;
  title: string;
  tags?: string[];
  text: string;
};

export const data: BlogCardType[] = [
  {
    id: 1,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review. What a delightful watching",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 2,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 3,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title:
      "Game of Thrones review Game of Thrones review Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 4,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 5,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 6,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 7,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 8,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 9,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
  {
    id: 10,
    img: "https://media.wired.com/photos/5bdb5fff134e755d734f7eeb/3:2/w_2560%2Cc_limit/Dany-Jon-GOT.jpg",
    createdAt: new Date().toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    title: "Game of Thrones review",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt pariatur nisi sunt nihil cum, eaque ut quisquam recusandae suscipit, perferendis voluptates consequuntur placeat perspiciatis optio fugit molestiae voluptas totam facilis.",
  },
];
